apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-api-config
  namespace: ml-api
  labels:
    app: ml-api
data:
  # Application configuration
  log_level: "INFO"
  workers: "4"
  max_requests: "1000"
  timeout: "60"

  # Model configuration
  model_name: "random_forest_classifier"
  model_version: "v1.0.0"

  # Feature configuration
  features: |
    feature1
    feature2
    feature3
    feature4
    feature5

  # Inference configuration
  batch_size: "32"
  inference_timeout: "5"

  # Monitoring configuration
  metrics_enabled: "true"
  metrics_port: "9090"
