apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-model-pvc
  namespace: ml-api
  labels:
    app: ml-api
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
