apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-api
  namespace: ml-api
  labels:
    app: ml-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ml-api
  namespace: ml-api
  labels:
    app: ml-api
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ml-api
  namespace: ml-api
  labels:
    app: ml-api
subjects:
- kind: ServiceAccount
  name: ml-api
  namespace: ml-api
roleRef:
  kind: Role
  name: ml-api
  apiGroup: rbac.authorization.k8s.io
