version: '3.8'

services:
  model-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: model-api
    ports:
      - "5000:5000"
    environment:
      - MODEL_NAME=${MODEL_NAME:-resnet50}
      - MODEL_DEVICE=${MODEL_DEVICE:-cpu}
      - API_PORT=5000
      - API_HOST=0.0.0.0
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
      - WORKERS=${WORKERS:-4}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    mem_limit: 2g
    cpus: 2.0
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge
