# Prometheus Configuration for Inference Gateway

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'local'
    environment: 'development'

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Inference Gateway application
  - job_name: 'inference-gateway'
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['inference-gateway:8000']
        labels:
          service: 'inference-gateway'
          environment: 'development'

# Recording rules for SLO calculations
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Alerting configuration (optional - for Exercise 05)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []  # Configure in Exercise 05
