name: mlflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - mlflow==2.8.0
    - scikit-learn==1.3.2
    - pandas==2.1.3
    - numpy==1.26.2
    - matplotlib==3.8.2
    - seaborn==0.13.0
    - boto3==1.29.7
    - google-cloud-storage==2.13.0
    - azure-storage-blob==12.19.0
