{{- if or .Values.secrets.apiKey .Values.secrets.dbPassword .Values.secrets.redisPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ml-api.fullname" . }}-secrets
  labels:
    {{- include "ml-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.apiKey }}
  api-key: {{ .Values.secrets.apiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.dbPassword }}
  db-password: {{ .Values.secrets.dbPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.redisPassword }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
  {{- end }}
{{- end }}
