version: '3.8'

services:
  # ML API Service (Development with hot reload)
  ml-api-dev:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    image: ml-api:dev
    container_name: ml-api-dev
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port
    environment:
      - MODEL_PATH=/models/model.pkl
      - DEBUG=true
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app:rw  # Mount source code for hot reload
      - ./models:/models:ro
    restart: unless-stopped
    networks:
      - ml-network-dev
    stdin_open: true
    tty: true

  # PostgreSQL Database (Development)
  postgres-dev:
    image: postgres:15-alpine
    container_name: ml-postgres-dev
    environment:
      - POSTGRES_DB=ml_db_dev
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - ml-network-dev

  # Redis (Development)
  redis-dev:
    image: redis:7-alpine
    container_name: ml-redis-dev
    ports:
      - "6379:6379"
    networks:
      - ml-network-dev

  # Adminer - Database GUI
  adminer:
    image: adminer:latest
    container_name: ml-adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres-dev
    depends_on:
      - postgres-dev
    networks:
      - ml-network-dev

volumes:
  postgres-dev-data:
    driver: local

networks:
  ml-network-dev:
    driver: bridge
