#!/bin/bash
###############################################################################
# Scenario 5: CUDA/GPU Not Available - Fix Script
###############################################################################
#
# Usage: ./fix.sh [--install-driver] [--setup-env] [--verify]
#

set -u

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}ℹ${NC} $*"; }
log_success() { echo -e "${GREEN}✓${NC} $*"; }
log_warning() { echo -e "${YELLOW}⚠${NC} $*"; }
log_error() { echo -e "${RED}✗${NC} $*"; }

# Default values
INSTALL_DRIVER=false
SETUP_ENV=false
VERIFY_ONLY=false
DRY_RUN=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --install-driver)
            INSTALL_DRIVER=true
            shift
            ;;
        --setup-env)
            SETUP_ENV=true
            shift
            ;;
        --verify)
            VERIFY_ONLY=true
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        -h|--help)
            cat << EOF
Usage: $0 [OPTIONS]

Fix CUDA/GPU availability issues.

Options:
  --install-driver      Install/update NVIDIA driver (requires reboot)
  --setup-env           Setup CUDA environment variables
  --verify              Verify GPU access only
  --dry-run             Show what would be done without doing it
  -h, --help            Show this help message

Examples:
  $0 --verify                    # Check if GPU is working
  $0 --setup-env                 # Setup environment variables
  $0 --install-driver            # Install NVIDIA driver (careful!)

Note: Installing drivers can break existing setups. Only use if needed.

EOF
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            exit 1
            ;;
    esac
done

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  CUDA/GPU Fix Utility                                      ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

if [ "$DRY_RUN" = true ]; then
    log_warning "DRY RUN MODE - No changes will be made"
    echo ""
fi

# Verify GPU
verify_gpu() {
    log_info "Verifying GPU access..."
    echo ""

    # Check hardware
    if lspci | grep -i nvidia &>/dev/null; then
        log_success "NVIDIA GPU detected"
    else
        log_error "No NVIDIA GPU found"
        return 1
    fi

    # Check driver
    if command -v nvidia-smi &>/dev/null && nvidia-smi &>/dev/null; then
        log_success "NVIDIA driver working"
        echo ""
        nvidia-smi --query-gpu=name,driver_version,memory.total --format=csv
    else
        log_error "NVIDIA driver not working"
        return 1
    fi

    echo ""

    # Check CUDA
    if command -v nvcc &>/dev/null; then
        cuda_version=$(nvcc --version | grep "release" | awk '{print $5}' | sed 's/,//')
        log_success "CUDA toolkit available: $cuda_version"
    else
        log_warning "CUDA toolkit not in PATH"
    fi

    # Check Python frameworks
    echo ""
    log_info "Checking Python frameworks..."

    python3 -c "
import sys
try:
    import torch
    print(f'  ✓ PyTorch: {torch.__version__}')
    print(f'  ✓ CUDA available: {torch.cuda.is_available()}')
    if torch.cuda.is_available():
        print(f'  ✓ GPU: {torch.cuda.get_device_name(0)}')
except ImportError:
    print('  ⚠ PyTorch not installed')
except Exception as e:
    print(f'  ✗ PyTorch error: {e}')
    sys.exit(1)
" 2>/dev/null

    return 0
}

# Setup environment variables
setup_environment() {
    log_info "Setting up CUDA environment variables..."
    echo ""

    # Find CUDA installation
    cuda_paths=(
        "/usr/local/cuda"
        "/usr/lib/cuda"
        "/opt/cuda"
    )

    cuda_home=""
    for path in "${cuda_paths[@]}"; do
        if [ -d "$path" ]; then
            cuda_home="$path"
            log_info "Found CUDA at: $cuda_home"
            break
        fi
    done

    if [ -z "$cuda_home" ]; then
        log_error "CUDA installation not found"
        echo ""
        log_info "Install CUDA toolkit first:"
        log_info "  sudo apt install nvidia-cuda-toolkit"
        return 1
    fi

    # Create environment setup script
    env_file="$HOME/.cuda_env"

    if [ "$DRY_RUN" = false ]; then
        cat > "$env_file" << EOF
# CUDA Environment Configuration
# Generated by fix.sh on $(date)

export CUDA_HOME=$cuda_home
export CUDA_PATH=\$CUDA_HOME
export PATH=\$CUDA_HOME/bin:\$PATH
export LD_LIBRARY_PATH=\$CUDA_HOME/lib64:\$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=\$CUDA_HOME/extras/CUPTI/lib64:\$LD_LIBRARY_PATH

# PyTorch/TensorFlow GPU settings
export CUDA_VISIBLE_DEVICES=0  # Use first GPU (modify as needed)
export TF_FORCE_GPU_ALLOW_GROWTH=true  # TensorFlow dynamic memory
EOF

        log_success "Created environment file: $env_file"
        echo ""

        # Add to shell rc files
        for rc_file in "$HOME/.bashrc" "$HOME/.zshrc"; do
            if [ -f "$rc_file" ]; then
                if ! grep -q "source $env_file" "$rc_file"; then
                    echo "" >> "$rc_file"
                    echo "# CUDA environment" >> "$rc_file"
                    echo "[ -f $env_file ] && source $env_file" >> "$rc_file"
                    log_success "Added to $rc_file"
                else
                    log_info "$rc_file already sources CUDA environment"
                fi
            fi
        done

        echo ""
        log_success "Environment configured"
        log_warning "Run 'source ~/.bashrc' or restart terminal to apply changes"
    else
        log_info "Would create: $env_file"
        log_info "Would update shell RC files"
    fi

    return 0
}

# Install NVIDIA driver
install_driver() {
    log_warning "Driver installation is a sensitive operation!"
    echo ""
    log_info "This will:"
    log_info "  1. Detect recommended driver version"
    log_info "  2. Install NVIDIA driver"
    log_info "  3. Blacklist conflicting nouveau driver"
    log_info "  4. Require system reboot"
    echo ""

    if [ "$DRY_RUN" = false ]; then
        read -p "Continue with driver installation? (yes/no): " confirm
        if [ "$confirm" != "yes" ]; then
            log_info "Installation cancelled"
            return 1
        fi
    fi

    echo ""
    log_info "Detecting GPU and recommended driver..."

    # Check if ubuntu-drivers is available
    if ! command -v ubuntu-drivers &>/dev/null; then
        log_error "ubuntu-drivers not found"
        log_info "Manual installation required:"
        log_info "  1. Check GPU: lspci | grep -i nvidia"
        log_info "  2. Find driver: apt search nvidia-driver"
        log_info "  3. Install: sudo apt install nvidia-driver-XXX"
        return 1
    fi

    # Show available drivers
    log_info "Available drivers:"
    ubuntu-drivers devices

    echo ""

    if [ "$DRY_RUN" = false ]; then
        log_info "Installing recommended driver..."

        # Update package lists
        sudo apt update

        # Install recommended driver
        sudo ubuntu-drivers autoinstall

        log_success "Driver installation initiated"
        echo ""

        # Blacklist nouveau
        log_info "Blacklisting nouveau driver..."
        sudo bash -c 'echo "blacklist nouveau" > /etc/modprobe.d/blacklist-nvidia-nouveau.conf'
        sudo bash -c 'echo "options nouveau modeset=0" >> /etc/modprobe.d/blacklist-nvidia-nouveau.conf'

        # Update initramfs
        sudo update-initramfs -u

        log_success "Driver installed"
        echo ""
        log_warning "REBOOT REQUIRED for changes to take effect!"
        log_info "Run: sudo reboot"
    else
        log_info "Would run:"
        echo "    sudo apt update"
        echo "    sudo ubuntu-drivers autoinstall"
        echo "    sudo update-initramfs -u"
        log_warning "Would require reboot"
    fi

    return 0
}

# Main execution
if [ "$VERIFY_ONLY" = true ]; then
    verify_gpu
    exit $?
fi

if [ "$INSTALL_DRIVER" = false ] && [ "$SETUP_ENV" = false ]; then
    log_info "No action specified. Use --help for options."
    echo ""
    log_info "Quick diagnostics:"
    verify_gpu
    echo ""
    log_info "Common fixes:"
    log_info "  --setup-env       Setup environment variables"
    log_info "  --install-driver  Install NVIDIA driver (requires reboot)"
    exit 0
fi

if [ "$SETUP_ENV" = true ]; then
    setup_environment
fi

if [ "$INSTALL_DRIVER" = true ]; then
    install_driver
fi

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  GPU Setup Guide                                           ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "1. VERIFY GPU HARDWARE"
echo "   lspci | grep -i nvidia"
echo ""

echo "2. INSTALL NVIDIA DRIVER"
echo "   Ubuntu/Debian:"
echo "     sudo ubuntu-drivers autoinstall"
echo "     sudo reboot"
echo ""
echo "   Or manually:"
echo "     sudo apt install nvidia-driver-525  # Replace with version"
echo ""

echo "3. INSTALL CUDA TOOLKIT"
echo "   Option A - Package manager (easier):"
echo "     sudo apt install nvidia-cuda-toolkit"
echo ""
echo "   Option B - Official installer (specific version):"
echo "     wget https://developer.download.nvidia.com/compute/cuda/..."
echo "     sudo sh cuda_*.run"
echo ""

echo "4. SETUP ENVIRONMENT"
echo "   Add to ~/.bashrc:"
echo "     export CUDA_HOME=/usr/local/cuda"
echo "     export PATH=\$CUDA_HOME/bin:\$PATH"
echo "     export LD_LIBRARY_PATH=\$CUDA_HOME/lib64:\$LD_LIBRARY_PATH"
echo ""

echo "5. INSTALL PYTHON PACKAGES WITH GPU SUPPORT"
echo "   PyTorch:"
echo "     pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118"
echo ""
echo "   TensorFlow:"
echo "     pip install tensorflow[and-cuda]"
echo ""

echo "6. VERIFY INSTALLATION"
echo "   nvidia-smi"
echo "   nvcc --version"
echo "   python -c 'import torch; print(torch.cuda.is_available())'"
echo ""

echo "7. TROUBLESHOOTING"
echo "   Driver not loaded:"
echo "     sudo modprobe nvidia"
echo "     lsmod | grep nvidia"
echo ""
echo "   Permission denied:"
echo "     sudo usermod -aG video \$USER"
echo "     sudo usermod -aG render \$USER"
echo "     # Then logout/login"
echo ""
echo "   Version mismatch:"
echo "     # Ensure PyTorch CUDA version matches installed CUDA"
echo "     # Check: nvidia-smi (supported CUDA version)"
echo "     # vs: torch.version.cuda"
echo ""

log_info "For detailed troubleshooting, run: ./investigate.sh"
echo ""
