# StatsD to Prometheus Metrics Mapping Configuration
#
# This file maps Airflow's StatsD metrics to Prometheus metrics format.
# Airflow emits metrics in StatsD format, and this exporter converts them
# to Prometheus metrics that can be scraped.

mappings:
  # DAG Processing Metrics
  - match: "airflow.dag_processing.last_duration.*"
    name: "airflow_dag_processing_last_duration"
    labels:
      dag_file: "$1"
      job: "airflow"

  - match: "airflow.dag_processing.last_run.seconds_ago.*"
    name: "airflow_dag_processing_last_run_seconds_ago"
    labels:
      dag_file: "$1"
      job: "airflow"

  - match: "airflow.dag_processing.processor_timeouts"
    name: "airflow_dag_processing_processor_timeouts"
    labels:
      job: "airflow"

  - match: "airflow.dag_processing.total_parse_time"
    name: "airflow_dag_processing_total_parse_time"
    labels:
      job: "airflow"

  # Scheduler Metrics
  - match: "airflow.scheduler.heartbeat"
    name: "airflow_scheduler_heartbeat"
    labels:
      job: "airflow"

  - match: "airflow.scheduler.tasks.killed_externally"
    name: "airflow_scheduler_tasks_killed_externally"
    labels:
      job: "airflow"

  - match: "airflow.scheduler.tasks.running"
    name: "airflow_scheduler_tasks_running"
    labels:
      job: "airflow"

  - match: "airflow.scheduler.tasks.starving"
    name: "airflow_scheduler_tasks_starving"
    labels:
      job: "airflow"

  - match: "airflow.scheduler.orphaned_tasks.cleared"
    name: "airflow_scheduler_orphaned_tasks_cleared"
    labels:
      job: "airflow"

  - match: "airflow.scheduler.orphaned_tasks.adopted"
    name: "airflow_scheduler_orphaned_tasks_adopted"
    labels:
      job: "airflow"

  # Executor Metrics
  - match: "airflow.executor.open_slots"
    name: "airflow_executor_open_slots"
    labels:
      job: "airflow"

  - match: "airflow.executor.queued_tasks"
    name: "airflow_executor_queued_tasks"
    labels:
      job: "airflow"

  - match: "airflow.executor.running_tasks"
    name: "airflow_executor_running_tasks"
    labels:
      job: "airflow"

  # DAG Run Metrics
  - match: "airflow.dagrun.dependency-check.*"
    name: "airflow_dagrun_dependency_check"
    labels:
      dag_id: "$1"
      job: "airflow"

  - match: "airflow.dagrun.duration.success.*"
    name: "airflow_dagrun_duration_success"
    labels:
      dag_id: "$1"
      job: "airflow"

  - match: "airflow.dagrun.duration.failed.*"
    name: "airflow_dagrun_duration_failed"
    labels:
      dag_id: "$1"
      job: "airflow"

  - match: "airflow.dagrun.schedule_delay.*"
    name: "airflow_dagrun_schedule_delay"
    labels:
      dag_id: "$1"
      job: "airflow"

  # Task Instance Metrics
  - match: "airflow.task.duration.*.*"
    name: "airflow_task_duration"
    labels:
      dag_id: "$1"
      task_id: "$2"
      job: "airflow"

  - match: "airflow.task_instance_created-*.*"
    name: "airflow_task_instance_created"
    labels:
      dag_id: "$1"
      task_id: "$2"
      job: "airflow"

  - match: "airflow.ti.start.*.*"
    name: "airflow_task_start"
    labels:
      dag_id: "$1"
      task_id: "$2"
      job: "airflow"

  - match: "airflow.ti.finish.*.*.*"
    name: "airflow_task_finish"
    labels:
      dag_id: "$1"
      task_id: "$2"
      state: "$3"
      job: "airflow"

  - match: "airflow.ti_failures"
    name: "airflow_task_failed"
    labels:
      job: "airflow"

  - match: "airflow.ti_successes"
    name: "airflow_task_success"
    labels:
      job: "airflow"

  # Pool Metrics
  - match: "airflow.pool.open_slots.*"
    name: "airflow_pool_open_slots"
    labels:
      pool: "$1"
      job: "airflow"

  - match: "airflow.pool.queued_slots.*"
    name: "airflow_pool_queued_slots"
    labels:
      pool: "$1"
      job: "airflow"

  - match: "airflow.pool.running_slots.*"
    name: "airflow_pool_running_slots"
    labels:
      pool: "$1"
      job: "airflow"

  # Operator Metrics
  - match: "airflow.operator_successes_*"
    name: "airflow_operator_successes"
    labels:
      operator: "$1"
      job: "airflow"

  - match: "airflow.operator_failures_*"
    name: "airflow_operator_failures"
    labels:
      operator: "$1"
      job: "airflow"

  # Smart Sensor Metrics
  - match: "airflow.smart_sensor_operator.poked_tasks"
    name: "airflow_smart_sensor_poked_tasks"
    labels:
      job: "airflow"

  - match: "airflow.smart_sensor_operator.poked_success"
    name: "airflow_smart_sensor_poked_success"
    labels:
      job: "airflow"

  - match: "airflow.smart_sensor_operator.poked_exception"
    name: "airflow_smart_sensor_poked_exception"
    labels:
      job: "airflow"

  # SLA Metrics
  - match: "airflow.sla_email_notification_failure"
    name: "airflow_sla_email_notification_failure"
    labels:
      job: "airflow"

  - match: "airflow.sla_missed"
    name: "airflow_sla_missed"
    labels:
      job: "airflow"

  # Default mapping for any unmatched metrics
  - match: "airflow.*"
    name: "airflow_${1}"
    labels:
      job: "airflow"
